### ISSUE TITLE
Add attribute name to empty error message

### ISSUE THREAD

**Issue by usatosi** [bloomberg/attrs-strict#20]
Hi, thank you for this very cool project!

** Is your feature request related to a problem? Please describe. **

When I set empty_ok to False and pass empty value to the attribute, I got the following error message.

> ValueError: Expected a non-empty attribute

When I have a class with many attributes, traceback doesn't help me to find out which attribute raise the error(see the sample below).

** Describe the solution you'd like **

Show attribute name in error message by having custom error class.

** Describe alternatives you've considered **
Your code raises ValueError on that case, but it seems to be easy to raise custom error like other part of your code.

** Additional context **

### sample code

```python
import attr
from attrs_strict import type_validator

@attr.s
class Sample:
    a = attr.ib(type=str, validator=type_validator(empty_ok=False))
    b = attr.ib(type=str, validator=type_validator(empty_ok=False))
    c = attr.ib(type=str, validator=type_validator(empty_ok=False))
    d = attr.ib(type=str, validator=type_validator(empty_ok=False))
    e = attr.ib(type=str, validator=type_validator(empty_ok=False))
    f = attr.ib(type=str, validator=type_validator(empty_ok=False))
    g = attr.ib(type=str, validator=type_validator(empty_ok=False))


s = Sample(
    a='foo',
    b='',
    c='foo',
    d='foo',
    e='foo',
    f='foo',
    g='foo'
)
```

### result

Trace back points the last line.

```shell
$ python try_attr_strict.py 
Traceback (most recent call last):
  File "try_attr_strict.py", line 22, in <module>
    g='foo'
  File "<attrs generated init __main__.Sample>", line 11, in __init__
  File "/home/satosi/.local/lib/python3.7/site-packages/attrs_strict/_type_validation.py", line 19, in _validator
    raise ValueError("Expected a non-empty attribute")
ValueError: Expected a non-empty attribute

```

### sample new error class

```python
class EmptyError(BadTypeError):
    def __init__(self, container, attribute):
        super(EmptyError, self).__init__()
        self.container = container
        self.attribute = attribute

    def __str__(self):
        error = "{} can not be empty and must be {} (got {})".format(
            self.attribute.name,
            self.attribute.type,
            self.container,
        )

        return self._render(error)
```

### result 2

```shell
$ python try_attr_strict.py 
Traceback (most recent call last):
  File "try_attr_strict.py", line 22, in <module>
    g='foo'
  File "<attrs generated init __main__.Sample>", line 11, in __init__
  File "/home/satosi/.local/lib/python3.7/site-packages/attrs_strict/_type_validation.py", line 20, in _validator
    raise EmptyError(field, attribute)
attrs_strict._error.EmptyError: b can not be empty and must be <class 'str'> (got )

```

**Comment by erikseulean** [comment]
Ok this seems like a nice thing to have, I can work on it in the near future but if you would like to implement it yourself feel free to send a PR linking this issue.

**Comment by erikseulean** [comment]
Thanks for contributing @usatosi
